### ISSUE TITLE
Relative symbolic link

### ISSUE THREAD

**Issue by baskerville** [soyuka/gulp-sym#1]
Could you provide an example on how to create a relative symlink?

**Comment by soyuka** [comment]
```
gulp
    .src('./source')
    .pipe(symlink(../../link', {relative: true}))
```

Sorry, bit late. 

Anyway, this module has been depreceated (forgot to mention it), have you tried https://github.com/ben-eb/gulp-symlink ?

**Comment by baskerville** [comment]
Thanks but I'm using _gulp-replace_ now.
