### ISSUE TITLE
symlink to a directory?

### ISSUE THREAD

**Issue by atomless** [soyuka/gulp-sym#2]
An example of how to symlink just a directory not all the files in a directory would be a very useful addition to the docs!

**Comment by soyuka** [comment]
This should symlink a directory:

```
gulp
    .src('/path/to/dir')
    .pipe(symlink('path/to/link'))
```

Therefore, this module has been depreceated, have you tried https://github.com/ben-eb/gulp-symlink ?

[Link to test source code](https://github.com/soyuka/gulp-sym/blob/master/test/index.js#L138)

**Comment by atomless** [comment]
Thanks I'll give it a try.
